name: Comment on Another Repository's Issue

on:
  deployment_status:


jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 33
          body: |
            /retry
          repository: 'CyberAgentHack/web-speed-hackathon-2024-scoring-tool'
          token: ${{ secrets.PAT }}